default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%=ENV['POSTRES_HOST']%>"
  username: "<%=ENV['POSTRES_USERNAME']%>"
  password: "<%=ENV['POSTRES_PASSWORD']%>"
  pool: 5

development:
  <<: *default
  database: railsgirls_development

test:
  <<: *default
  database: railsgirls_test
